### ISSUE TITLE
Exception while attempting to download twitter video

### ISSUE THREAD

**Issue by solonovamax** [JunkFood02/Seal#1107]
I was attempting to download a video from twitter and I got an exception. However, attempting to download it a second time caused it to work properly.

Perhaps this was caused due to a race condition, as I started the download very quickly after opening the app.

Also, I have cookies set for the twitter.com domain to my account.

```
App version: 1.10.0-(F-Droid) (11004)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.09.24

URL: https://twitter.com/8bunme_yyu/status/1705398591546925455?t=GjDdhuEOURUA-_rWcpW3wQ&s=19
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 19, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 21, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/aes.py", line 6, in <module>
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 548, in _get_data
zipimport.ZipImportError: bad local file header: '/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp'
```

**Comment by solonovamax** [comment]
Update: the same issue has occurred again:

```
App version: 1.10.0-(F-Droid) (11004)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.10.07

URL: https://twitter.com/8bunme_yyu/status/1709548028535927197?t=JJIsz1BzLu6RXFN3hMx2MA&s=19
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 20, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/__init__.py", line 26, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 14, in <module>
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 548, in _get_data
zipimport.ZipImportError: bad local file header: '/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp'
```

I *believe* it may (?) have something to do with a race condition where it attempts to fetch an update for `yt-dlp` on startup after x amount of time, and at the same time, a user initiates a download.

**Comment by JunkFood02** [comment]
lmao this bot keeps closing this issue. Anyway, I'll look into it

**Comment by solonovamax** [comment]
bot moment
