### ISSUE TITLE
can't download because problem with downloading subtitles 

### ISSUE THREAD

**Issue by abdullahamin665** [JunkFood02/Seal#1161]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

App version: 1.10.0 (11000)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.10.13

URL: https://youtu.be/Cgx46Wnrusc?si=r4tGMXkLSuOut3KY
ERROR: Unable to download video subtitles for 'en-ehkg1hFWq8A': [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']

**Comment by GfEW** [comment]
Exact same error message here, see below. I remember seeing it once before, about 6 weeks ago. As it occurs so infrequently, I find it hard to track it down, and so far, cannot attribute it to any particular triggers or circumstances. The only additional context I'm currently able to provide is the following log entries:

> 12-20 06:57:07.655 W/System.err( 3927): 	at androidx.fragment.app.Fragment$4.run(SourceFile:14)
> 12-20 06:57:07.655 W/System.err( 3927): 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:96)
> 12-20 06:57:07.655 W/System.err( 3927): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
> 12-20 06:57:07.655 W/System.err( 3927): 	at com.junkfood.seal.ui.page.download.DownloadViewModel$startDownloadVideo$2.invokeSuspend(SourceFile:177)
> 12-20 06:57:07.655 W/System.err( 3927): 	at com.yausername.youtubedl_android.YoutubeDL.execute$default(Unknown Source:11)
> 12-20 06:57:07.655 W/System.err( 3927): 	at com.yausername.youtubedl_android.YoutubeDL.execute(SourceFile:3)
> 12-20 06:57:07.655 W/System.err( 3927): com.yausername.youtubedl_android.YoutubeDLException: ERROR: [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']
> 12-20 06:56:47.781 W/System.err( 4404): 	at android.os.HandlerThread.run(HandlerThread.java:65)

Please note that most of these entries share the same timestamp, hence may have actually occurred in any order. I wouldn't rely on the order they are displayed.

**Comment by unforgettablerose** [comment]
Just now experienced this problem after having updated the app to v1.11.2

**Comment by JunkFood02** [comment]
We couldn't find a stable way to reproduce this issue yet, but I guess this is because the filesystem of the device is temporarily mounted as read-only, at least in our python runtime environment, which should be considered as a system bug. A workaround should work is to reboot your device. We'll continue to investigate this further

**Comment by unforgettablerose** [comment]
I don't know what happened, but it seems to have resolved on its own. But it was an issue during the time of the update, like in the immediate time after the update.

**Comment by GfEW** [comment]
Of the roughly six youtube videos I've encountered this error with last month, exactly one self-healed by rebooting the phone. The other ones still threw the error - go figure.

However, I finally might have found a real hint to underlying problem:
**The error correlates to the available formats the video is provided in.** 

In my today's test series of 8 different download attempts, 
* each of the 4 videos that were available in webm format (possibly along with mp4) didn't throw the error. 
* each of the 4 videos that were only avialable as mp4, did throw the error. 

If in Seal Settings --> Format"" --> "Preferred video format", I switched back from "Quality" (my default) to "Legacy", the video download succeeded regardless of webm being available or not. In other words, the error only occured to me while Seal's option"Preferred video format" was set to "Quality"! 

I've also tried to test it the other way around (i. e. "Legacy" setting with webm-only videos , but couldn't find any webm video that didn't also come with a few mp4 options.

Given this new insight, the curious "self-healing" mentioned above could result from the video being transcoded and made available as webm that very moment.

**Comment by JunkFood02** [comment]
@GfEW Could you switch `Format selection` to `Custom`, and try to reproduce this error for a specific format code? It would be better if there is a video link related to this issue

**Comment by GfEW** [comment]
I'm not sure what exactly you're referring to. The slider `Format selection` in the Advanced section of Format setting is enabled already. Ist that what you're asking for?

Re video link: I'm totally aware of that miss, sorry about it. I just need to find a vid meaningless enough before sharing it here.


Off topic: Discussions like this one would be a major use cases of a "show internal yt-dlp command" option in Seal. Being able to c&p the internally used yt-dlp command, including all employed options and arguments, would be handy here. 
Suggesting such an improvement has long been on my list, I just haven't gotten around to actually create the issue and elaborate. Hope I'll find time ASAP..

**Comment by JunkFood02** [comment]
Quality or Legacy in format preference only affects the order of the formats. The `Suggested` format in the format selection page is just the first format in the list, so if you suspected specific format causes this issue, just remember the format code of it and verify if it can be reproduced

![telegram-cloud-photo-size-5-6181296042138516034-y](https://github.com/JunkFood02/Seal/assets/69683722/decd479f-d89b-487f-a841-18a7099ea730)

**Comment by GfEW** [comment]
Sorry, while editing my previous answer to make it clearer, I didn't notice yours. Please see above.

**Comment by JunkFood02** [comment]
> This error, however, occurs at the start of step 3, preventing Seal from fetching that list of available audio/video formats, and me from checking and possibly adjusting any selection.

The app runs yt-dlp commands for twice for a download:
- Fetch the video information and all of its available formats
- Actually download the selected format of the video

Based on your description, the `No usable temporary directory` error occurred in the first request which **does not**  download any files, thus it's unrelated to your "Format preference", whatever it's `Legacy` or `Quality`

**Comment by JunkFood02** [comment]
@GfEW 

I'll just download the video on my own every time when I notice a user posting report of this issue with related video URL attached. But **none of them** could be reproduced on my device.

Reinstalling won't work for this issue, either, according to a few feedbacks

**Comment by GfEW** [comment]
After further systematic testing, the correlation looks like more than accidental statistics. For the first time, it allows me to **reproduce occurrence/non-occurrence of the error**, although so far, only in a tiny confined space of two binary parameters:
1. video URL (can be "OK" or "problematic")
2. preferred video format (can be "Quality" or "Legacy").

So far, "problematic" videos can be identified by the following two properties:
* they are from that specific channel, and
* their format selection view (when fetched with format pref "Legal") lists only mp4 formats.

(Lacking video examples that have only one of these properties, it is still unclear which property causes the problem.)

Even with video links that I've never tested before: if 
1. the video is
"problematic", and 
2. Seal's preferred video format is set to "Quality", and 
3. I attempt to fetch the list of available formats,
then the `No usable temporary directory found` error occurs.

As of now, the following little results table holds, without a single exception in 26 tests:

`         |  vid OK  | vid probl `
`quality |     +    |    -     `
`legacy  |     +    |    +     `
where 
`+` success
`-` error.

In order to allow you to also reproduce these findings, I'm still trying to find other affected videos or channels, hope I can provide you with working, sharable examples soon.

**Comment by GfEW** [comment]
@JunkFood02 
> I'll just download the video on my own every time when I notice a user posting report

Maybe we are interacting with some sort of transcoding automatism on the side of youtube here? Like: 
1. Many yt users upload their videos as mp4, still using legacy codecs.
2. As long as a video has very few views (being very new or unpopular), transcoding is only in the pipeline, or youtube doesn't bother transcoding at all. 
3. But once the video gains popularity, transcoding is done. 
4. As soon as the video is also available as webm, the error vanishes?

Both video URLs posted in this issue by @abdullahamin665 and @FoxTrotte were very new at that time.

**Comment by GfEW** [comment]
2 h of binge testing various arcane channels/videos has, instead of the hoped-for triggers, brought up _one_ video that is _neither_ transcoded _nor_ "problematic". How confusing!

Also, some of my yesterday's failing examples have stopped failing. (Most videos in the same "problematic" channel still do fail.)

These news invalidate my proposal that "problematic" videos
> can be identified by the following two properties:
> * they are from that specific channel, and
> * their format selection view (when fetched with format pref "Legal") lists only mp4 formats.

Instead, "problematic" videos rather seem to be a proper subset of all videos with those two properties.

Here are the core points to this issue I've gathered so far, including a few side notes:

1. The error occurs in the "fetching format list" stage, only with certain videos and only if preferred video format is set to "quality".
2. For any affected video, switching format pref to "legacy" circumvents the error. (Switching back to "quality" makes the error occur again.)
3. For any affected video, switching to "audio" also circumvents the error. (Switching back to "video" makes the error occur again.)
4. Video tracks of all affected videos are solely available as mp4, whilst most (but not all) non-affected videos also offer webm.
5. Affected videos tend to have low view counts (being very new, or unpopular).
6. Some of the errors resolve on their own, mostly in a matter of days (hours?). The video format list is then fetchable, and the formerly "problematic" video downloadable. No example of a change in the opposite direction (formerly "OK", now "problematic") is known.
7. Restarting the device, emptying Seal's app cache, deleting its data or reinstalling Seal - all these measures don't seem to help. (But mind point 6. above.)

**Comment by GfEW** [comment]
I'm sorry I still haven't been able to give a particular failing video link. Due to the either obscure or transitory nature of affected videos, searching for sharable examples got too time consuming, I had to stop it for a while.
However, I've kept occasionally following odd links possibly leading to videos (momentarily) unpopular enough to trigger the error, and indeed, found one today: 
https://www.youtube.com/watch?v=PoesvM362bk
Beware, it is spam. Also, it might stop failing - or even existing - anytime.

@JunkFood02 
According your suggestion, I've also examined that video link with "Format sorting" a bit, and found this difference:
* `vcodec:vp9.2,res:360,acodec:opus,abr~64` _fails_ (this is the original "import" line)
* `vcodec:av1,res:360,acodec:opus,abr~64` _fails_
* `vcodec:av01,res:360,acodec:opus,abr~64` _fails_
* `res:360,acodec:opus,abr~64` _works_
* `vcodec:avc1,res:360,acodec:opus,abr~64` _works_
* `vcodec:foobar,res:360,acodec:opus,abr~64` interestingly also _works_.

Whilst switching to "Audio" (cf. no. 3 in above "core points") still works to fetch the list of formats even with format sorting keys including `vcodec:vp9.2`, "Preferred video format: Legacy" (cf  no. 2) doesn't make a difference anymore when "Format sorting" is enabled - it then _fails_ just like "Quality" does.

I'm not sure how `vcodec:vp9.2` gets into the "imported" sorting string. Anyway, including it indeed appears to provide a second way to trigger the same error with this "problematic" video that doesn't offer any webm option (with video codec vp9 or av1) in its available formats list.

**Comment by GfEW** [comment]
> @JunkFood02
> 
> > I'll just download the video on my own every time when I notice a user posting report
> 
> Maybe we are interacting with some sort of transcoding automatism on the side of youtube here? Like:
> 
> 1. Many yt users upload their videos as mp4, still using legacy codecs.
> 2. As long as a video has very few views (being very new or unpopular), transcoding is only in the pipeline, or youtube doesn't bother transcoding at all.
> 3. But once the video gains popularity, transcoding is done.
> 4. As soon as the list of available formats of that video also includes webm, the error vanishes.

I think we can treat this explanation as a given, by now. Therefore, there's little use in providing you with ever new video link examples, most of them just stop failing too soon. (Usually, that's within less than a day, and the exceptions to this rule tend to be extremely "arcane" channels (like double digit view counts) - it wouldn't feel right for me to expose them here.)

However, I have finally found a "more robustly public" yt channel where you have a high chance of finding "problematic" videos by yourself anytime: 
https://www.youtube.com/channel/UCmuTmpLY35O3csvhyA6vrkg

Just try the five most recent videos posted there, the newer the better. Should (rarely) none of them trigger the error, give it some hours for new videos to appear, then try again. At this very moment, three out of the newest five do trigger the error. 

Hope that helps. :-)

**Comment by GfEW** [comment]
@JunkFood02 
As this is marked as "help wanted", is there any other than actual code level work left that I could contribute for this persisting issue to progress?

**Comment by rudelf** [comment]
Hello everyone!!! I decided to join the discussion and share my findings with you.
I should note that almost all users who had to come to this issue for help, this error is caused by an attempt to download content from YouTube.
I can assume that this error occurs when the link to the video looks like: `https://youtu.be/AAAAAAAAAAA?si=BBBBBBBBBBBBBBBBB`
where:
`AAAAAAAAAAA` - unique 11-characters ID of the video on YouTube platform;
`?si=BBBBBBBBBBBBBBBBBBBBBBBBBBB` - suffix added when copying link from YouTube app by "Share" button action
Let me explain why this aspect drew my attention to itself.
The thing is that the PC-version of the yt-dlp console utility behaves unpredictably when entering a link with suffix `'?si=...'`.
Even when attempting to fetch formats with such a link with this suffix appended, the utility immediately proceeds to the video downloading stage.
Thus, this behavior of Seal app (which also uses yt-dlp utility as its basis) requiring access to the temporary directory at the fetching process, becomes clear.
I suggest users to manually get rid of the suffix `'?si=...'` in the link to problematic videos for the time being.
And after reports on successful downloads using the method I suggested, it will be possible to find solutions for automatic shortening of links to the correct format.

**Comment by GfEW** [comment]
@rudelf 
I'd really like this long standing issue to progress, but I cannot reproduce your findings on my devices. 

Since I've developed a habit of stripping all unnecessary parts like the si=... (supposedly, session ID) from the URL long ago, all error reports provided to this issue by me were based on just the core video URL, e. g. https://www.youtube.com/watch?v=PoesvM362bk or, equivalently, https://youtu.be/PoesvM362bk . 

You could try the same by copying the video link from wherever you find it, then quickly editing it e. g. in [simple clipboard editor](https://www.f-droid.org/en/packages/com.trianguloy.clipboardeditor/), then 'sharing' it with Seal.

So far, on my side, the only key difference that reliably allows to either trigger the error or to successfully fetch the list of available formats at will, is the one described [here](https://github.com/JunkFood02/Seal/issues/1161#issuecomment-1939375983). 
(Alas, the video channel mentioned there has stopped being a worthwhile source of problematic videos.)

**Comment by JunkFood02** [comment]
Thanks for all the efforts on this!

Though it's difficult to reproduce this issue and get a detailed stacktrace, we're working on updating the built-in python environment for Seal recently, which could possibly solve this issue.

**Comment by GfEW** [comment]
Re stacktrace: 
Would it help if I provided more log excerpts like to the one in https://github.com/JunkFood02/Seal/issues/1161#issuecomment-1863945038 ?

If I knew how to inspect the current yt-dlp command line (for a generic suggestion, see #1337), I'd have started experimenting with more vebose yt-dlp modes in termux months ago, and likely be able to provide a much more detailled picture of the error by now. 

(I still don't have the time to familiarize myself with the vast range of yt-dlp options to a degree that would allow me to blindly rebuild the yt-dlp command internally used by Seal without seeing it, but in general, I'm comfortable with CLI. It's really the GUI/CLI barrier in Seal that prevents me from examining this issue via custom commands or on the command line.)

**Comment by JunkFood02** [comment]
> Would it help if I provided more log excerpts like the one in https://github.com/JunkFood02/Seal/issues/1161#issuecomment-1863945038?

I'm afraid not. The error itself does not have any relevant information reflected in the logs, any of them, so that we can only guess its cause based on some clumsy A/B testing. And these attempts are even not reproducible, like I've never met this error on my own when download from YouTube

**Comment by GfEW** [comment]
> The error itself does not have any relevant information reflected in the logs, any of them

Do you actually think more useful information _could_ be retrieved on the commandline with some of yt-dlp's [verbosity options](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#verbosity-and-simulation-options), or am I beating a dead horse there?

> so that we can only guess its cause based on some clumsy A/B testing

If you've never met this error in person, I can understand being drawn to that hypothesis ... 
Just how could A/B testing explain the reproducibility in "quality" mode on my end (with yt video URLs that offer no vp9 or av1 (webm) stream) on three different devices over various tested uplinks, which furthermore get resolved reliably by switching to "legacy"? 
*puzzled*

**Comment by JunkFood02** [comment]
> Do you actually think more useful information could be retrieved on the commandline with some of yt-dlp's [verbosity options](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#verbosity-and-simulation-options)

We've already enabled this with `Detailed output` on, and so far I think we haven't got any other information than the error `No usable temporary directory found` itself.

> or am I beating a dead horse there?

Absolutely not! We've been tracking this error for months, receiving lots of error reporting regarding *different* videos and download configurations. The lesson we learnt is actually that, the issue is too complicated for us to get a minimal reproducible sample, find the root cause, and solve it by patching it in our code or yt-dlp.

Moreover, it's probably a combination from a corrupted python environment(the `termux` part) and a specific set of download configuations and/or a specific video. That said, this could more likely to be an indication of an bad build than a bug that needs to be fixed. What needs to be fixed is the build itself.

**Comment by GfEW** [comment]
Thanks a lot for this elaboration, @JunkFood02 . It provides several formerly missing pieces that allow to understand the problem with this issue, and your handling thereof, much better now.

If I find the time, I'll try to reproduce the error in an android emulator. That way, it should become reproducible for you guys, too.

**Comment by jetlagg3d** [comment]
Having the same error here with most links, like https://youtu.be/U_LlX4t0A9I.

**Comment by GfEW** [comment]
@jetlagg3d
> Having the same error here with most links, like https://youtu.be/U_LlX4t0A9I.

At the time of your post, that video link was younger than 12 hours, which fits well into the pattern described [here](https://github.com/JunkFood02/Seal/issues/1161#issuecomment-1939375983).
By now, it has gathered 34 million views. Based on my findings from extensive tests (see above), such popular videos are expected to "self heal" in less than a day. Indeed, I'm able to download it already, even with "Quality" format preference (which otherwise would trigger the error).

Have you tried to download it more recently again?

**Comment by jetlagg3d** [comment]
> Have you tried to download it more recently again?
Actually, it works now. A few minutes after I posted this I kept retrying and it eventually worked. I didn't know it takes a while for new videos, thanks!
