### ISSUE TITLE
Can not download video from Smotrim.ru

### ISSUE THREAD

**Issue by Ilya-Ezhik** [JunkFood02/Seal#1317]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When trying to download a video from the site, the following error appears

### To Reproduce

1. Go to SMOTRIM App
2. Choose Video
3. Click "share" and choose Seal
4. Set the video parameters for download
5. Press "Download"!

### Error reports

App version: 1.11.3 (11132)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.01.31.232703

URL: https://smotrim.ru/video/2753943
[debug] Command-line config: ['--no-mtime', '-v', '--no-playlist', '--concurrent-fragments', '16', '-S', 'proto,vcodec:h264,ext', '--embed-chapters', '-P', '/storage/emulated/0/Download/Seal', '-P', 'temp:/storage/emulated/0/Download/Seal/tmp', '-o', '%(title).200B [%(id)s].%(ext)s', '--no-cache-dir', '--ffmpeg-location', '/data/app/~~tZETZnsYPb0ZyyEyKH2kGQ==/com.junkfood.seal-K2Hz9am2v57bvidcvn0f6g==/lib/arm64/libffmpeg.so', 'https://smotrim.ru/video/2753943']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version nightly@2024.01.31.232703 from yt-dlp/yt-dlp-nightly-builds [fc2cc626f] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-4.14.186-27218697-aarch64-with-libc (OpenSSL 1.1.1t  7 Feb 2023, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.17, mutagen-1.46.0, sqlite3-3.30.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1829 extractors
[debug] Sort order given by user: proto, vcodec:h264, ext
[debug] Sort order given by extractor: source
[debug] Formats sorted by: hasvid, ie_pref, proto, vcodec:h264(7), vext, aext, source, lang, quality, res, fps, hdr:12(7), channels, acodec, size, br, asr, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking http downloader on "https://cdn-v.smotrim.ru/_cdn_auth/secure/v/vh/mp4/fhd-wide/002/946/321.mp4?auth=mh&vid=2946321"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3417, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3138, in dl
    return fd.download(name, new_info, subtitle)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/http.py", line 364, in real_download
    establish_connection()
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 4081, in urlopen
    return self._request_director.send(req)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

### Screenshots & Screen Records

![Screenshot_20240202_070139](https://github.com/JunkFood02/Seal/assets/130345901/9a5a0f69-d293-4bbf-a241-17ab583463ec)

### Additional context

After selecting all the download options, the application provides video download options, but choosing the recommended one, this error appears

**Comment by JunkFood02** [comment]
HTTP Error 403: Forbidden means your ip is blocked by that site
