### ISSUE TITLE
1.12.0-beta.1 crash report

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#1364]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

App version: 1.12.0-beta.1 (11132)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.12.30

java.util.NoSuchElementException: List is empty.
 at kotlin.collections.CollectionsKt.first(SourceFile:2)
 at com.junkfood.seal.util.PreferenceUtil.getTemplate(SourceFile:44)
 at com.junkfood.seal.util.DownloadUtil.executeCommandInBackground$default(SourceFile:9)
 at com.junkfood.seal.Downloader$executeCommandWithUrl$1.invokeSuspend(Unknown Source:32)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
 at kotlinx.coroutines.DispatchedTask.run(Unknown Source:96)
 at androidx.core.app.ActivityRecreator$1.run(SourceFile:15)
 at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)
 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [DeferredCoroutine{Cancelling}@dace11d, Dispatchers.IO]

**Comment by JunkFood02** [comment]
Does this issue occur in `Quick download` with `Configure before download` off?

**Comment by Botan626** [comment]
> Does this issue occur in `Quick download` with `Configure before download` off?

yes
