### ISSUE TITLE
[Bug Report] Permission denied error with the --cookies option

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#140]
### Describe the bug

I'm trying to download an album from YT-Music using the following command:
`--yes-playlist --extract-audio --audio-format opus --audio-quality 0 --cookies /storage/emulated/0/ Download/Seal/cookies.txt`

### Error reports & Screenshots

It keeps trying to download and then fails and copy this error:
```
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 953, in main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 945, in _real_main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 889, in __exit__
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 1555, in save
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 1510, in open
PermissionError: [Errno 13] Permission denied: '/storage/emulated/0/Download/Seal/cookies.txt'
```

https://user-images.githubusercontent.com/41828058/185748251-f2f3ac22-9d72-446b-bf27-a49ea0c0dbc9.mp4

### Device info

1.0.5 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]

**Comment by JunkFood02** [comment]
Cannot reproduce. Do you have a typo in the cookies path, like a blank typed by accident?

**Comment by JunkFood02** [comment]
- https://github.com/yausername/dvd/issues/70#issue-1340699066

**Comment by Marco-9456** [comment]
> Edit: I've figured out where the problem is. Please use this command to create a `cookies.txt` file generated by yt-dlp, and then edit it. Let's see if there's still the same error

It worked, and the quality increase is very noticeable, thanks for the help brother 👍 😀

**Comment by Marco-9456** [comment]
> > Edit: I've figured out where the problem is. Please use this command to create a `cookies.txt` file generated by yt-dlp, and then edit it. Let's see if there's still the same error
> 
> It worked, and the quality increase is very noticeable, thanks for the help brother 👍 😀

But there's something that I've noticed,
Downloading using costum commands is much faster then using the already provided options.

**Comment by JunkFood02** [comment]
>Downloading using costum commands is much faster then using the already provided options.

That's because Seal fetches info from every item in playlist for storing it in the database. Executing custom command doesn't need this. I'll look into the possibility for asynchronous operations with the multitasking major updates.

**Comment by Marco-9456** [comment]
> > Downloading using costum commands is much faster then using the already provided options.
> 
> That's because Seal fetches info from every item in playlist for storing it in the database. Executing custom command doesn't need this.

Thanks for the explanation

>I'll look into the possibility for asynchronous operations with the multitasking major updates.

I'll be waiting for it 😀
