### ISSUE TITLE
[Bug Report] Download Errors

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#153]
### Describe the bug

Im trying to download the following playlist that I've made: [Playlist](https://music.youtube.com/playlist?list=PLr9VyW7d01CApe4unvpGAG3WJ3d7keQ7c&feature=share)

### To Reproduce

This is the Custom command that I'm using:
`--ignore-errors --yes-playlist --extract-audio -f bestaudio --audio-quality 0 --embed-thumbnail --parse-metadata %(album,genre,track,playlist,title)s:%(meta_album)s --embed-metadata -o %(playlist_title)s/%(title).60s.%(ext)s --cookies /storage/emulated/0/Download/Seal/cookies.txt`

And the playlist link: https://music.youtube.com/playlist?list=PLr9VyW7d01CApe4unvpGAG3WJ3d7keQ7c&feature=share

### Error reports & Screenshots

1. **Sometimes i get this report:**

```
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 953, in main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 945, in _real_main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 889, in __exit__
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 1555, in save
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 1510, in open
PermissionError: [Errno 13] Permission denied: '/storage/emulated/0/Download/Seal/cookies.txt'

```

1. **And sometimes this one:**

```
ERROR: audio conversion failed: file:/storage/emulated/0/Download/Seal/Video/mix/RED.opus: File exists
ERROR: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov
ERROR: audio conversion failed: file:/storage/emulated/0/Download/Seal/Video/mix/Wrath.opus: File exists
ERROR: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov
ERROR: audio conversion failed: file:/storage/emulated/0/Download/Seal/Video/mix/INTERWORLD - PERSONALITY (MEMPHIS 66.6 EXCLUSIVE).opus: File exists
ERROR: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 953, in main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 945, in _real_main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 889, in __exit__
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 1555, in save
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 1510, in open
PermissionError: [Errno 13] Permission denied: '/storage/emulated/0/Download/Seal/cookies.txt'
```

### Device info

1.2.0-beta.1 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]

### Additional context

What I've noticed is that it's Downloading the Playlist sometimes in `opus` format and sometimes in `webm` which doesn't support merging the thumbnail as cover.

If you need more details please let me know 😃

**Comment by Marco-9456** [comment]
Creating a new cookies.txt file solved the problem.

**Comment by JunkFood02** [comment]
> What I've noticed is that it's Downloading the Playlist sometimes in opus format and sometimes in webm which doesn't support merging the thumbnail as cover.

`-x` = extract the opus audio file from the audio-only webm container got from `-f ba`
