### ISSUE TITLE
Sponsorblock [Feature Request]

### ISSUE THREAD

**Issue by mativiters** [JunkFood02/Seal#163]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

I want a GUI for removing parts of videos with SponsorBlock. I already do that with cuustom commands, but GUI would be very much appreciated.

**Comment by JunkFood02** [comment]
Which command do you use?

**Comment by mativiters** [comment]
I have made this template as a custom command:
yt-dlp -f "best[height=720]" --sponsorblock-remove all

Then I use it together with a  youtube video/channel/playlist

and it works like a charm. I successfully have downloaded entire channels with this (Sponsor parts of the video are removed)

You can also provide ability to change SponsorBlock-api, and what kinds of Sponsors to be removed (ponsor, intro, outro,
selfpromo, preview, filler, interaction,
music_offtopic, poi_highlight, all)

https://github.com/yt-dlp/yt-dlp#sponsorblock-options

**Comment by JunkFood02** [comment]
I see. So we can just make `--sponsorblock-remove` as default and let users to filled out which categories they want to remove

**Comment by mativiters** [comment]
Yes!
Here's a video that has sponsors in it:
https://www.youtube.com/watch?v=SrcupdKGvBs&t=589

**Comment by JunkFood02** [comment]
Added in v1.2.0-beta.4

**Comment by Marco-9456** [comment]
> Added in v1.2.0-beta.4

I think it's broken 
![Screenshot_20220828-173105_Seal](https://user-images.githubusercontent.com/41828058/187082024-d0a85355-79e2-4877-af1f-7ca317b792af.jpg)

`ERROR: Postprocessing: Conversion failed!`

**Comment by JunkFood02** [comment]
I encountered the same error with this video, but it seems to be a video-specific problem. Videos under the same account tested fine

**Comment by Marco-9456** [comment]
> I encountered the same error with this video, but it seems to be a video-specific problem. Other videos under the same account tested fine

I will probably never use this option but i just wanted to test out of curiosity 😅

**Comment by PacaAlpaca** [comment]
I tried with 3-4 videos from different channels and in one time (i changed settings froma all to all,-filler) it worked well but in rest I get same error as above at the end of conversion

**Comment by JunkFood02** [comment]
> I tried with 3-4 videos from different channels with sponsorblock marks (i changed settings from `all `to `all,-filler`) and in one time it worked well but in rest I get same error as above at the end of conversion


Basically, SponserBlock works by downloading a video and then truncating some of its sections before stitching them together, an operation related to its video encoding format and FFmpeg. I haven't reproduced such problems on my PC with yt-dlp and the latest FFmpeg.
Thus, I think the problem could be linked to the format of the video files and the FFmpeg build version of the library but cannot confirm. 
CC @xibr (Sorry for bothering you again 🙏)

**Comment by xibr** [comment]
Please can you give some links as examples?

I have tried with this command.
with set format `yt-dlp -f "best[height=720]" --sponsorblock-remove all https://www.youtube.com/watch?v=SrcupdKGvBs`
```
[youtube] SrcupdKGvBs: Downloading webpage
[youtube] SrcupdKGvBs: Downloading android player API JSON
[youtube] SrcupdKGvBs: Downloading player c57c113c
[SponsorBlock] Fetching SponsorBlock segments
[SponsorBlock] Found 6 segments in the SponsorBlock database
[info] SrcupdKGvBs: Downloading 1 format(s): 22
[download] Destination: /sdcard/Download/youtubedl-android/YET ANOTHER package format, and Ubuntu might not get this GNOME feature - Linux & Open Source News.mp4

[download]   0.0% of 96.47MiB at  105.07KiB/s ETA 15:53
[download]   0.0% of 96.47MiB at  196.22KiB/s ETA 08:26
[download]   0.0% of 96.47MiB at  344.45KiB/s ETA 04:48
[download]   0.0% of 96.47MiB at  100.06KiB/s ETA 16:27
[download]   0.0% of 96.47MiB at  147.98KiB/s ETA 11:07
[download]   0.1% of 96.47MiB at  206.60KiB/s ETA 07:58
[download]   0.1% of 96.47MiB at  310.94KiB/s ETA 05:17
[download]   0.3% of 96.47MiB at  472.97KiB/s ETA 03:28
[download]   0.5% of 96.47MiB at  778.02KiB/s ETA 02:06
[download]   1.0% of 96.47MiB at    1.26MiB/s ETA 01:15
[download]   2.1% of 96.47MiB at    1.76MiB/s ETA 00:53
[download]   4.1% of 96.47MiB at    2.45MiB/s ETA 00:37
[download]   8.3% of 96.47MiB at    3.26MiB/s ETA 00:27
[download]  12.4% of 96.47MiB at    3.73MiB/s ETA 00:22
[download]  16.6% of 96.47MiB at    3.99MiB/s ETA 00:20
[download]  20.7% of 96.47MiB at    4.28MiB/s ETA 00:17
[download]  24.9% of 96.47MiB at    4.57MiB/s ETA 00:15
[download]  29.0% of 96.47MiB at    4.57MiB/s ETA 00:14
[download]  33.2% of 96.47MiB at    4.87MiB/s ETA 00:13
[download]  37.3% of 96.47MiB at    5.04MiB/s ETA 00:11
[download]  41.5% of 96.47MiB at    5.03MiB/s ETA 00:11
[download]  45.6% of 96.47MiB at    5.25MiB/s ETA 00:09
[download]  49.7% of 96.47MiB at    5.45MiB/s ETA 00:08
[download]  53.9% of 96.47MiB at    5.49MiB/s ETA 00:08
[download]  58.0% of 96.47MiB at    5.55MiB/s ETA 00:07
[download]  62.2% of 96.47MiB at    5.35MiB/s ETA 00:06
[download]  65.9% of 96.47MiB at    5.47MiB/s ETA 00:06
[download]  70.1% of 96.47MiB at    5.61MiB/s ETA 00:05
[download]  74.2% of 96.47MiB at    5.64MiB/s ETA 00:04
[download]  78.4% of 96.47MiB at    5.74MiB/s ETA 00:03
[download]  82.5% of 96.47MiB at    5.74MiB/s ETA 00:02
[download]  86.6% of 96.47MiB at    5.56MiB/s ETA 00:02
[download]  90.2% of 96.47MiB at    5.62MiB/s ETA 00:01
[download]  94.3% of 96.47MiB at    5.68MiB/s ETA 00:00
[download]  98.5% of 96.47MiB at    5.76MiB/s ETA 00:00
[download] 100.0% of 96.47MiB at    5.80MiB/s ETA 00:00
[download] 100% of 96.47MiB in 00:17 at 5.55MiB/s      
[ModifyChapters] Removing chapters from /sdcard/Download/youtubedl-android/YET ANOTHER package format, and Ubuntu might not get this GNOME feature - Linux & Open Source News.mp4
Deleting original file /sdcard/Download/youtubedl-android/YET ANOTHER package format, and Ubuntu might not get this GNOME feature - Linux & Open Source News.uncut.mp4 (pass -k to keep)
```
without set format `yt-dlp --sponsorblock-remove all https://www.youtube.com/watch?v=SrcupdKGvBs`
```
[debug] Command-line config: ['--verbose', '-o', '/sdcard/Download/youtubedl-android/%(title)s.%(ext)s', '--sponsorblock-remove', 'all', 'https://youtu.be/SrcupdKGvBs', '--no-cache-dir', '--ffmpeg-location', '/data/app/com.yausername.youtubedl_android_example-9XoEn0j3dEvljT9Ch-WY4g==/lib/arm64/libffmpeg.so']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (zip)
[debug] Python 3.8.0 (CPython 64bit) - Linux-4.4.111-21427293-aarch64-with-libc (libc)
[debug] Checking exe version: /data/app/com.yausername.youtubedl_android_example-9XoEn0j3dEvljT9Ch-WY4g==/lib/arm64/libffmpeg.so -bsfs
[debug] Checking exe version: /data/app/com.yausername.youtubedl_android_example-9XoEn0j3dEvljT9Ch-WY4g==/lib/arm64/libffprobe.so -bsfs
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Optional libraries: mutagen-1.45.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] [youtube] Extracting URL: https://youtu.be/SrcupdKGvBs
[debug] [youtube] Decrypted nsig HChp_Kf5efdv1NwO8q => nAKgGt-c-feZRw
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/873d?service=YouTube&categories=%5B%22outro%22%2C+%22music_offtopic%22%2C+%22selfpromo%22%2C+%22sponsor%22%2C+%22intro%22%2C+%22preview%22%2C+%22filler%22%2C+%22interaction%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%5D
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking http downloader on "https://rr8---sn-bpb5oxu-3c2r.googlevideo.com/videoplayback?expire=1662090570&ei=6igRY_rUJNjvgQfivIOgCg&ip=104.28.197.182&id=o-AMa6_ae5mwJznTE42jqQGeGCm3_oNSPpvsMFYH5Nks6l&itag=303&source=youtube&requiressl=yes&mh=Wr&mm=31%2C29&mn=sn-bpb5oxu-3c2r%2Csn-4g5edndl&ms=au%2Crdu&mv=m&mvi=8&pcm2cms=yes&pl=24&initcwndbps=193750&spc=lT-KhiAQ7n3kV87AB7Cw_1Ok2uEtgQ4&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=195662927&dur=970.886&lmt=1661623702427947&mt=1662068723&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=4437434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANUeSVvQgHHXRnMihttQuKAkXCk1ph-kxUzKU6jInqYpAiAHCKhoVDC2-Oq_qYDowiH1Plw0WSTy6xKL_sBBtib5oA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhALaRSlNv3MzehXt8XkN0Sn1nAPQXy7cJoYKn1r7AnsuZAiEAojPAR8GrDEf0oyBOdJIcatkUZIRRKMfjuHXTwwZuMic%3D"
[debug] Invoking http downloader on "https://rr8---sn-bpb5oxu-3c2r.googlevideo.com/videoplayback?expire=1662090570&ei=6igRY_rUJNjvgQfivIOgCg&ip=104.28.197.182&id=o-AMa6_ae5mwJznTE42jqQGeGCm3_oNSPpvsMFYH5Nks6l&itag=251&source=youtube&requiressl=yes&mh=Wr&mm=31%2C29&mn=sn-bpb5oxu-3c2r%2Csn-4g5edndl&ms=au%2Crdu&mv=m&mvi=8&pcm2cms=yes&pl=24&initcwndbps=193750&spc=lT-KhiAQ7n3kV87AB7Cw_1Ok2uEtgQ4&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=13900640&dur=970.921&lmt=1661614956199167&mt=1662068723&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMVefkNOZI6-VkP5rT30fo-4V6oW3sYiP4_b9vbMkWyzAiAyJA99K6_lYbHIt-OpwawMJItEwSDyj0aPFQ9QStJBzw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhALaRSlNv3MzehXt8XkN0Sn1nAPQXy7cJoYKn1r7AnsuZAiEAojPAR8GrDEf0oyBOdJIcatkUZIRRKMfjuHXTwwZuMic%3D"
[debug] ffmpeg command line: /data/app/com.yausername.youtubedl_android_example-9XoEn0j3dEvljT9Ch-WY4g==/lib/arm64/libffmpeg.so -y -loglevel repeat+info -i 'file:/sdcard/Download/youtubedl-android/YET ANOTHER package format, and Ubuntu might not get this GNOME feature - Linux & Open Source News.f303.webm' -i 'file:/sdcard/Download/youtubedl-android/YET ANOTHER package format, and Ubuntu might not get this GNOME feature - Linux & Open Source News.f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:/sdcard/Download/youtubedl-android/YET ANOTHER package format, and Ubuntu might not get this GNOME feature - Linux & Open Source News.temp.webm'
[debug] ffprobe command line: /data/app/com.yausername.youtubedl_android_example-9XoEn0j3dEvljT9Ch-WY4g==/lib/arm64/libffprobe.so -hide_banner -show_format -show_streams -print_format json 'file:/sdcard/Download/youtubedl-android/YET ANOTHER package format, and Ubuntu might not get this GNOME feature - Linux & Open Source News.webm'
[debug] Concat spec = 18.262000-40.512000, 102.004000-831.845000, 896.861000-898.728000, 926.605000-931.143000
[debug] Writing concat spec to /sdcard/Download/youtubedl-android/YET ANOTHER package format, and Ubuntu might not get this GNOME feature - Linux & Open Source News.temp.webm.concat
[debug] ffmpeg command line: /data/app/com.yausername.youtubedl_android_example-9XoEn0j3dEvljT9Ch-WY4g==/lib/arm64/libffmpeg.so -y -loglevel repeat+info -hide_banner -nostdin -f concat -safe 0 -i 'file:/sdcard/Download/youtubedl-android/YET ANOTHER package format, and Ubuntu might not get this GNOME feature - Linux & Open Source News.temp.webm.concat' -map 0 -dn -ignore_unknown -c copy -movflags +faststart 'file:/sdcard/Download/youtubedl-android/YET ANOTHER package format, and Ubuntu might not get this GNOME feature - Linux & Open Source News.temp.webm'
[debug] Input #0, concat, from 'file:/sdcard/Download/youtubedl-android/YET ANOTHER package format, and Ubuntu might not get this GNOME feature - Linux & Open Source News.temp.webm.concat':
  Duration: 00:12:38.50, start: -3.914000, bitrate: 0 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 59.94 fps, 59.94 tbr, 1k tbn, 1k tbc
    Metadata:
      DURATION        : 00:16:10.886000000
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      DURATION        : 00:16:10.921000000
Output #0, webm, to 'file:/sdcard/Download/youtubedl-android/YET ANOTHER package format, and Ubuntu might not get this GNOME feature - Linux & Open Source News.temp.webm':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 59.94 fps, 59.94 tbr, 1k tbn, 1k tbc
    Metadata:
      DURATION        : 00:16:10.886000000
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      DURATION        : 00:16:10.921000000
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
[concat @ 0x74e6660000] DTS 22114 < 22245 out of order
[webm @ 0x74e6661200] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 26159 >= 26028
av_interleaved_write_frame(): Invalid argument
frame= 1570 fps=0.0 q=-1.0 Lsize=    7631kB time=00:00:26.16 bitrate=2389.6kbits/s speed= 259x    
video:7265kB audio:351kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.204012%
Conversion failed!

ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3247, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3424, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3406, in run_all_pps
    info = self.run_pp(pp, info)
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3385, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/modify_chapters.py", line 58, in run
    in_out_files = [remove_chapters(info['filepath'], False)]
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/modify_chapters.py", line 56, in remove_chapters
    return file, self.remove_chapters(file, cuts, concat_opts, self._force_keyframes and not is_sub)
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/modify_chapters.py", line 316, in remove_chapters
    self.concat_files([in_file] * len(concat_opts), out_file, concat_opts)
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 415, in concat_files
    self.real_run_ffmpeg(
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 361, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

```

**Comment by JunkFood02** [comment]
Yeah, the logs indicate that the problem is related to the video format. YouTube will provide mp4(AVC1 codec) for resolutions under 720p and WebM(VP9 codec) only for resolutions over 1080p. I did not encounter this problem with yt-dlp on my PC. So I guess the problem lies in the low version of FFmpeg which cannot handle certain video encodings

**Comment by JunkFood02** [comment]
@PacaAlpaca

We have bumped up the version of FFmpeg which seems cause this problem, please do some test with CI artifacts of [the latest commit](https://github.com/JunkFood02/Seal/actions/runs/3006020628)

**Comment by PacaAlpaca** [comment]
I tested version `Seal-1.3.0-beta.1-arm64-v8a` and it works great with videos with multiple SponsorBlock marks.
Thank You :)

**Comment by pukkandan** [comment]
> [webm @ 0x74e6661200] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 26159 >= 26028


See https://github.com/yt-dlp/yt-dlp/issues/871 for details about the issue and possible workarounds

---

I recommend setting the default to `--sponsorblock-remove default` instead of `all`. Currently, `default` => `all,-filler`. This could change in future to accomodate what the categories recommended for removal are (in case Sponsorblock adds even more categories)
