### ISSUE TITLE
using an unsupported version of Python [fixed itself?]

### ISSUE THREAD

**Issue by gd0666** [JunkFood02/Seal#1824]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I regularly download music with seal from YouTube which has worked until recently.
If I remember I had the same bug on my other android device which is an OPPO but was able to fix it by clearing the cache and updating the yt-dlp.

On my phone, used exclusively for music and outdoor activities however said fix didn't work.
I tried downloading another video in my preferred settings (max quality, audio only, convert to mp3) which has a length of 2:37 which worked just fine.

The only thing I'd say might be a cause is the fact that the video is 3h long and it might be "too much"?
Which I think is bs, since I've downloaded 4h+ videos without a hitch and it didn't refer to Python being the issue.

**EDIT: ** As I tried reproducing the bug in order to provide screenshots it suddenly simply worked...
Since I am definitely not schizophrenic and the bug might provide some benefit as feedback I am still going to post it

As always, thanks for your insanely great app. I can't even tell you how much I appreciate each and everyone contributing to such a great project.
And sorry if my bug report is lacking. 

### To Reproduce

1. Go to _URL: https://m.youtube.com/watch?v=iwaig04vZu4_
2. Copy and paste (or share) into Seal
3. Try downloading in the above mentioned settings
4. ???
5. Profit

### Error reports

App version: 1.13.0-(F-Droid) (11301)
Device information: Android 11 (API 30)
Supported ABIs: [armeabi-v7a, armeabi]
Yt-dlp version: 2024.10.25.232902

URL: https://m.youtube.com/watch?v=iwaig04vZu4
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 4, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.9 and above are supported by yt-dlp

### Screenshots & Screen Records

![Screenshot_2024-10-26-22-38-06-989_com junkfood seal](https://github.com/user-attachments/assets/9f9db1ad-cb07-488b-8515-4d40535eaeb2)

### Additional context

**Additional Infos about my phone:**

Redmi Note 9A (M2006C3LG)
MIUI Global / 12.5.7 stable / 12.5.7(RCDEUXM)
32GB Storage 
2GB Ram
CPU Helio G25 Octa-core Max. 2Ghz
Android 11 RPA.200720.11
KERNEL 4.19.127-perf-ga0b9294047ee
Baseband MOLY.LR12A.R3.MP.V134.1.P75
The "add 0.5 GB RAM" option is disabled since it just works when you have enough disk space apparently 
Banged up because of daily use in the outdoors
below 1GB Storage left
Has no Sim
Doesn't support 5G or 5Ghz WiFi 
If you haven't used that specific phone it is **insanely slow** and can't even run two apps at the same time without one of them crashing.
If you're actively downloading something changing from viewing the progress to let's say just looking at the desktop/home screen may lead to a crash

Final note: it took 15 minutes for the download to finish on a steady 6Mbit wifi connection.

**Comment by Noitarud** [comment]
I came on to say I got a similar error, it failed saying python too old "Only Python versions 3.9 and above are supported by yt-dlp" however the issue is I refused all the updates of seal - how could it now not want to use the 3.8 that was installed?
Presently 1.12.0

**Comment by gd0666** [comment]
> I came on to say I got a similar error, it failed saying python too old "Only Python versions 3.9 and above are supported by yt-dlp" however the issue is I refused all the updates of seal - how could it now not want to use the 3.8 that was installed? Presently 1.12.0

That would make you the third person that I've seen in the issues section  of this app that has the same problem. 
Pretty sure this isn't just our fault but something worth of a fix.
In the meantime maybe try the steps I took for a possible **workaround** :

- close Seal
- restart phone
- tap and hold app symbol (of seal)
- go to an option named "app info" or "about"
- look for the option to delete the cache
- launch seal
- try downloading another video
- if successful download the original intended video 

Hope that works for you, my guy.

**Comment by bashonly** [comment]
update seal to version 1.13.1

**Comment by gd0666** [comment]
> update seal to version 1.13.1

The newest available version on F-Droid is 1.13.0 though.
And I am way too lazy to look up another way to side load apps especially when it seems like it fixed itself.

**Comment by Noitarud** [comment]
I still had "auto update" ticked - so what might have happened was it checked for the latest version of seal and updated yt-dlp without user consent and then nagged user to update seal. If so I could go "back" to 12 if I disable github checking (provided all checking is disabled by that)

**Comment by bashonly** [comment]
> obviously yt-dlp people need to signify major changes

We announced we would be removing support for Python 3.8 in October 2024 [back at the beginning of June](https://github.com/yt-dlp/yt-dlp/issues/10086) and pinned it to the top of our issue tracker.

We added a [deprecation warning to the program in September](https://github.com/yt-dlp/yt-dlp/commit/cca534cd9e6850c70244f225a4a1895ef4bcdbec#diff-cb61015f2453f43450b250b9786cca428a9680b9409c3bfd80bdb5825446e29e) and [made another announcement in the changelog](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.09.27) before the removal of Python 3.8 support.

We have added [yet another announcement](https://github.com/yt-dlp/yt-dlp/commit/c998238c2e76c62d1d29962c6e8ebe916cc7913b#diff-323808d1d1a45be3d06ea051c76192878238cd5c25e74087fbdad00eab2c6a16) to the changelog of [all releases that have removed Python 3.8 support](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/tag/2024.10.23.232902). **Note that we have not even removed 3.8 support from yt-dlp *stable* releases yet**. This change has only been made in nightly/master so far.

The Python Software Foundation itself stopped supporting Python 3.8 completely on 2024.10.07. 

> maybe by major version increment and if they do that

yt-dlp uses calendar versioning, so no such thing could be done.
