### ISSUE TITLE
Unable to download 

### ISSUE THREAD

**Issue by Legion4200** [JunkFood02/Seal#1846]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

App version: 1.13.0 (11302)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.11.04.232933

URL: https://www.youtube.com/live/bNR02UE7tEs?si=A_8atnaJQ1O-Dlps
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 4, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.9 and above are supported by yt-dlp

### Error reports

App version: 1.13.0 (11302)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.11.04.232933

URL: https://www.youtube.com/live/bNR02UE7tEs?si=A_8atnaJQ1O-Dlps
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 4, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.9 and above are supported by yt-dlp

**Comment by bashonly** [comment]
you need to update Seal to version 1.13.1 (update **Seal**, not yt-dlp)

**Comment by Gitical-thinker** [comment]
This happened to me once i updated to the latest ytdlp version. I then tried the nightly one as well. Both wouldn't work. Subsequent reinstallations of seal have also failed.

**Comment by seproDev** [comment]
@Gitical-thinker What seal version do you have installed? You will need version 1.13.1 which you can get from here: https://github.com/JunkFood02/Seal/releases/tag/v1.13.1
Do not install it from any sealapk website. Those are all fake and potentially contain malware. The only official place to get seal from is this GitHub repo.

**Comment by Gitical-thinker** [comment]
@seproDev Thanks! Downloading the apk directly from this site has given me a working version.

I don't know why the versions on F-Droid suddenly no longer worked for me, as I have the current version with the newest yt-dlp on another phone working just fine. Anyways, the fresh install using this sites' apk solved the problem.
