### ISSUE TITLE
Can't Download YT Music 

### ISSUE THREAD

**Issue by notjannielle** [JunkFood02/Seal#1847]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Hi. I cant properly download youtube music playlist. Before it was working but now it was not. It was always showing that error whenever i download a music even not playlist. It shows that bug after i pasted the link and press download button.,

### To Reproduce

1. Go to youtube music 
2. search for playlist
3. copy playlist link
4. paste playlist link
5. error shown

### Error reports

App version: 1.13.0-(F-Droid) (11302)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.11.04

URL: [https://music.youtube.com/playlist?list=RDCLAK5uy_mygsXSPH6yvTzhhqQD22oVvHT6lF_DkoY&playnext=1](https://music.youtube.com/playlist?list=RDCLAK5uy_mygsXSPH6yvTzhhqQD22oVvHT6lF_DkoY&playnext=1&fbclid=IwZXh0bgNhZW0CMTAAAR1xu-VemWznBy-M-gH20yFqnDg3iI3PBMRImzuJCIyCID664cyWp_JPqcY_aem_u2zFcnuSNCRbZx3iyAVeiQ)
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 4, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.9 and above are supported by yt-dlp

### Screenshots & Screen Records

![image](https://github.com/user-attachments/assets/5615f1b6-e5f4-40a7-a8a0-d1c1a8eaaacc)
![image](https://github.com/user-attachments/assets/c760f4fa-4627-4dcc-b52d-c7a6a9241705)

### Additional context

It was working before, i didnt update nor modified the app settings.

**Comment by bashonly** [comment]
update Seal to version 1.13.0 (update **Seal**, not yt-dlp)
