### ISSUE TITLE
[Bug Report] - New Cookies option

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#185]
### Describe the bug

Can you please clarify how to use the new cookies option, because it's not working for me.

### To Reproduce

I enabled the option and copied the content of the cookies.txt file and pasted it in the new cookies option.

### Error reports & Screenshots

<details markdown='1'><summary>Show</summary>
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 18, in <module>
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 962, in main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 924, in _real_main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 721, in __init__
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3763, in _setup_opener
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 106, in load_cookies
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 1617, in load
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py", line 2014, in _really_load
    raise LoadError(
http.cookiejar.LoadError: '/data/user/0/com.junkfood.seal/cache/cookies.txt' does not look like a Netscape format cookies file
</details>

### Device info

App version: 1.2.0-beta.6 (10100)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2281 x 1080

### Additional context

I know that I'm doing something wrong probably because the error says that the `cookies.txt does not look like a Netscape format cookies file`

**Comment by Marco-9456** [comment]
Jus realized that i should've copied literally the whole content of the cookies.txt file.
It's working now
