### ISSUE TITLE
App crash when try to  download video

### ISSUE THREAD

**Issue by eaglu** [JunkFood02/Seal#223]
### Describe the bug

app crash when hit download button

### To Reproduce

1.input video link or just a character
2.hit download button
3.hit start download button

### Error reports & Screenshots

time: 1663224829694
msg: java.lang.IllegalArgumentException: Service not registered: com.junkfood.seal.MainActivity$a@18d4bf1
stacktrace: java.lang.IllegalArgumentException: Service not registered: com.junkfood.seal.MainActivity$a@18d4bf1
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1880)
	at android.app.ContextImpl.unbindService(ContextImpl.java:2036)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:846)
	at com.junkfood.seal.MainActivity$b.a(SourceFile:2)
	at com.junkfood.seal.ui.page.download.DownloadViewModel$e.k(SourceFile:15)
	at r8.a.y(Unknown Source:8)
	at i9.m0.run(Unknown Source:86)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Suppressed: i9.k0: [y1{Cancelling}@e08d7f0, Dispatchers.Main.immediate]

### Device info

App version: 1.3.0 (10300)
Device information: Android 12 (API 32)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2454 x 1095

**Comment by JunkFood02** [comment]
Please provide the link to the video

**Comment by eaglu** [comment]
sorry for not being clear,it will crash even just input a character.

junkfood ***@***.***> 于 2022年9月15日周四 下午3:12写道：

**Comment by JunkFood02** [comment]
:ok_hand:

**Comment by JunkFood02** [comment]
Fixed in v1.3.1
