### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by KaranBharti666** [JunkFood02/Seal#339]
### Describe the bug

I tried many times but any video, music not downloading? 

### Error reports & Screenshots

Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 18, in <module>
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 966, in main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 928, in _real_main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 721, in __init__
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3792, in _setup_opener
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 108, in load_cookies
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 1624, in load
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py", line 2014, in _really_load
    raise LoadError(
http.cookiejar.LoadError: '/data/user/0/com.junkfood.seal/cache/cookies4D0wj6F0B4Q.txt' does not look like a Netscape format cookies file

### Device info

Infinix Note 11

**Comment by JunkFood02** [comment]
Turn off cookies or use a valid cookies.txt file's content
