### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by chaithu1897** [JunkFood02/Seal#407]
### Describe the bug

iam new to seal and yt dlp commads .i run a thumail command and i get this code .and i want a little bit of help in yt dlp comands 

--write-thumbnail --convert-thumbnails png --skip-download

### Error reports & Screenshots

[debug] Command-line config: ['-P', '/storage/emulated/0/Download/Seal', '--config-locations', '/data/user/0/com.junkfood.seal/cache/config.txt', '-v', '--cookies', '/data/user/0/com.junkfood.seal/cache/cookies.txt', '--no-cache-dir', '--ffmpeg-location', '/data/app/com.junkfood.seal-7K9Ve6VljK6b7qaHIxa0RA==/lib/arm64/libffmpeg.so', 'https://youtu.be/TBVcTgM-l24']
[debug] | Config "/data/user/0/com.junkfood.seal/cache/config.txt": ['--write-thumbnail', '--convert-thumbnails', 'png', '--skip-download']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.11.11 [8b64402] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-4.9.186-perf-g10af704-aarch64-with-libc (OpenSSL 1.1.1d  10 Sep 2019, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: mutagen-1.46.0, sqlite3-2.6.0
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/_main_.py", line 17, in <module>
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/_init_.py", line 968, in main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/_init_.py", line 928, in _real_main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 641, in _init_
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3777, in print_debug_header
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3806, in _setup_opener
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 108, in load_cookies
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 1653, in load
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py", line 2014, in _really_load
    raise LoadError(
http.cookiejar.LoadError: '/data/user/0/com.junkfood.seal/cache/cookies.txt' does not look like a Netscape format cookies file

### Device info

App version: 1.7.0-beta.3 (10610)
Device information: Android 10 (API 29)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2027 x 1078

**Comment by Marco-9456** [comment]
Try disabling the Cookies option.

**Comment by chaithu1897** [comment]
> Try disabling the Cookies option.

thank u brother this one solved my issue
