### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by D4rklord07** [JunkFood02/Seal#420]
### Describe the bug

Error on downloading a song from yt music

### Error reports & Screenshots

Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 968, in main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 928, in _real_main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 729, in __init__
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3806, in _setup_opener
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 108, in load_cookies
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 1653, in load
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py", line 2014, in _really_load
    raise LoadError(
http.cookiejar.LoadError: '/data/user/0/com.junkfood.seal/cache/cookiesYkIaECfGubo.txt' does not look like a Netscape format cookies file

### Device info

App version: 1.7.0-beta.2 (10610)
Device information: Android 9 (API 28)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 1964 x 1078

**Comment by Marco-9456** [comment]
- maybe the Cookies file is not valid or 
- look at the formating, it should look like this: 
![Screenshot_20221212_094942_Kiwi Browser](https://user-images.githubusercontent.com/41828058/207001669-5702c4c5-586d-4679-ad58-25199a0a5fac.jpg)

**Comment by th3dm4** [comment]
I have the same problem and app version is 1.6.1.

**Comment by th3dm4** [comment]
I have the same problem and app version is 1.6.1

**Comment by th3dm4** [comment]
I have the same problem and app version is 1.6.1. I solved the problem by switch off "Cookies", which in "Setting—Network—Cookies". You can try it

**Comment by JunkFood02** [comment]
> I have the same problem and app version is 1.6.1. I solved the problem by switch off "Cookies", which in "Setting—Network—Cookies". You can try it

Switch to v1.7.0-rc.1, the app will generate valid cookies for you
