### ISSUE TITLE
[Bug Report] Unable to download instagram stories

### ISSUE THREAD

**Issue by Stef-00012** [JunkFood02/Seal#467]
### Describe the bug

When I try to download a instagram story I always get same error

### To Reproduce

1. Copy URL to any instagram story
2. Paste it on Seal
3. Try to Download it
4. See the error

### Error reports & Screenshots

ERROR: [instagram:story] 3004135155572342131: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Device info

App version: 1.6.1-(F-Droid) (10614)
Device information: Android 13 (API 33)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2192 x 1079

The phone is a "Samsung Galaxy A33 5G" (SM-A336B)

**Comment by Stef-00012** [comment]
A video

https://user-images.githubusercontent.com/81536172/210053643-c851e0e5-b4e7-488f-84fc-04446d459172.mp4

**Comment by JunkFood02** [comment]
Have you generated cookies for Instagram and enabled it?

**Comment by Stef-00012** [comment]
> Have you generated cookies for Instagram and enabled it?

how do i generate tge cookies for Instagram?

**Comment by JunkFood02** [comment]
Settings - Network - Cookies

**Comment by Stef-00012** [comment]
> Settings - Network - Cookies

after i enabled the cookies button i got an error asking to add `--password` and `--username`
i tried setting both username or mail as `--username` but i always get this error

`Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 968, in main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 928, in _real_main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 729, in __init__
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3806, in _setup_opener
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 108, in load_cookies
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 1653, in load
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py", line 2014, in _really_load
    raise LoadError(
http.cookiejar.LoadError: '/data/user/0/com.junkfood.seal/cache/cookies.txt' does not look like a Netscape format cookies file`

**Comment by JunkFood02** [comment]
> Have you generated cookies for Instagram?

You need to manually input the URL and log-in with your account

**Comment by Stef-00012** [comment]
> > Have you generated cookies for Instagram?
> 
> You need to manually input the URL and log-in with your account

Netscaped format is like
`ab=1234; cd="5678` ?

(also where is `cookies.txt` file located?, in the text input i tried directly putting the cookies and putting the path to a file `.txt` with the cookies but none of 2 worked)

**Comment by JunkFood02** [comment]
I've described clearly how to generate cookies with your account.
