### ISSUE TITLE
Permission denied error when accessing termux directory 

### ISSUE THREAD

**Issue by SWAYOM** [JunkFood02/Seal#478]
### Describe the bug

I can't download any  . Bro WTH 🙃🙃🙃🙃neither can i download anything from YouTube , Twitter , pinterest , etc... It doesn't even download just audio.... I keep the settings as default.. but still nothing.... WTH bro... Ijust updated it  to 1.7.0 hope this time it works... Can u help me with the issue 

### Device info

SEAL 🦭 V 1.7.0 [F-DROID]

**Comment by BobbyESP** [comment]
Go to Settings > General > Detailed Output and try to download a video. Send here what the app says.

**Comment by cod-md** [comment]
I have tha same can't download anything

Detailed Output 

Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/__init__.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/__init__.py", line 38, in <module>
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/plugins.py", line 136, in load_plugins
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/plugins.py", line 120, in iter_modules
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/plugins.py", line 97, in find_spec
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/plugins.py", line 72, in search_locations
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/plugins.py", line 62, in _get_package_paths
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/pathlib.py", line 1389, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/pathlib.py", line 1180, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/data/data/com.termux/files/home/yt-dlp-plugins'

**Comment by cod-md** [comment]
I just uninstalled termux app and seal worked fine lol 😂 
I am a genius 😎

**Comment by JunkFood02** [comment]
> I just uninstalled termux app and seal worked fine

This is a weird issue, it seems the yt-dlp inside Seal tried to access directory of termux by accident. Did you install termux with yt-dlp or no?

**Comment by Marco-9456** [comment]
> Yeah, I have termux with yt-dlp and I'm also getting the same error, probably have something to do with the new yt-dlp update

This is really a weird bug, i have Termux with the latest yt-dlp update and it never happened to me.

**Comment by SWAYOM** [comment]
> > I just uninstalled termux app and seal worked fine
> 
> This is a weird issue, it seems the yt-dlp inside Seal tried to access directory of termux by accident. Did you install termux with yt-dlp or no?

what does termux do at all...bro can u make me understand it the function of termux in seal or the function of termux at all

**Comment by SWAYOM** [comment]
> > I just uninstalled termux app and seal worked fine
> 
> This is a weird issue, it seems the yt-dlp inside Seal tried to access directory of termux by accident. Did you install termux with yt-dlp or no?

what does termux do at all...bro can u make me understand it the function of termux in seal or the function of termux at all

**Comment by BobbyESP** [comment]
This bug happened to me with my spotdl-android library. Seems like the library takes as home the termux emulated storage. What I've made in my lib was to put in the enviroment a variable called HOME. See this: 

- https://github.com/BobbyESP/spotdl-android/blob/1a968e47e01a1d4365508f27b077fe3a61ae7bc9/library/src/main/java/com/bobbyesp/library/SpotDL.kt#L57
- https://github.com/BobbyESP/spotdl-android/blob/1a968e47e01a1d4365508f27b077fe3a61ae7bc9/library/src/main/java/com/bobbyesp/library/SpotDL.kt#L111
- https://github.com/BobbyESP/spotdl-android/blob/1a968e47e01a1d4365508f27b077fe3a61ae7bc9/library/src/main/java/com/bobbyesp/library/SpotDL.kt#L270

**Comment by BobbyESP** [comment]
Hope that that info helped

**Comment by JunkFood02** [comment]
It seems like the problem is with [this line](https://github.com/yausername/youtubedl-android/blob/master/library/src/main/java/com/yausername/youtubedl_android/YoutubeDL.java#L220), termux somehow puts its directory to system environment variable, causing the library to search yt-dlp plugins in it.

When manually specifying `HOME` variable, the python would ignore the `PATH` for dependencies, but I still doubt about why the `PYTHONHOME` was ignored.

**Comment by JunkFood02** [comment]
Since the OP is using F-Droid builds, we'd better release a patch for it

**Comment by BobbyESP** [comment]
Okay!
