### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by binsonjose** [JunkFood02/Seal#489]
### Describe the bug

App version: 1.7.2 (10720)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.02

URL: https://www.instagram.com/reel/ClFleB1gP6x/?igshid=MDJmNzVkMjY=
/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py:2070: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py", line 2043, in _really_load
    assert domain_specified == initial_dot
AssertionError

  _warn_unhandled_exception()
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py", line 2043, in _really_load
    assert domain_specified == initial_dot
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 970, in main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 930, in _real_main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 732, in __init__
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3853, in _setup_opener
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 108, in load_cookies
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 1661, in load
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py", line 2071, in _really_load
    raise LoadError("invalid Netscape format cookies file %r: %r" %
http.cookiejar.LoadError: invalid Netscape format cookies file '/data/user/0/com.junkfood.seal/cache/cookies.txt': 'instagram.com\tTRUE\t/\tTRUE\t0\tig_did\t8E1CB797-97E0-4EEF-9D11-38362B28F564'

### Error reports & Screenshots

App version: 1.7.2 (10720)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.02

URL: https://www.instagram.com/reel/ClFleB1gP6x/?igshid=MDJmNzVkMjY=
/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py:2070: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py", line 2043, in _really_load
    assert domain_specified == initial_dot
AssertionError

  _warn_unhandled_exception()
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py", line 2043, in _really_load
    assert domain_specified == initial_dot
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 970, in main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 930, in _real_main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 732, in __init__
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3853, in _setup_opener
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 108, in load_cookies
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 1661, in load
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py", line 2071, in _really_load
    raise LoadError("invalid Netscape format cookies file %r: %r" %
http.cookiejar.LoadError: invalid Netscape format cookies file '/data/user/0/com.junkfood.seal/cache/cookies.txt': 'instagram.com\tTRUE\t/\tTRUE\t0\tig_did\t8E1CB797-97E0-4EEF-9D11-38362B28F564'
![Screenshot_2023-01-06-20-25-44-13_2b0c70832456616f1f794bb05bb8d2fa](https://user-images.githubusercontent.com/24862001/211037172-ce21d69c-5837-43e8-99a0-7f67f3fe81d2.jpg)

**Comment by BobbyESP** [comment]
As your traceback says, your Netscape cookeis file is bad formatted

**Comment by JunkFood02** [comment]
Did you try to remove and re-generate cookies for it?
