### ISSUE TITLE
Cant download Twitter and Instagram videos 

### ISSUE THREAD

**Issue by AliRazaMaka** [JunkFood02/Seal#650]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Cant download Twitter and Instagram videos to sd card and phone 

### To Reproduce

1.go to share button
2. Quick seal or seal download
3.Ceck seal 
4. Could not fetch the video. Message pop up.

### Error reports

App version: 1.8.2 (10820)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.02.17

URL: https://twitter.com/Collectionofal1/status/1631719109443350529?t=cx777mygjWeYO3hBzixBkg&s=09
/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py:2070: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py", line 2043, in _really_load
    assert domain_specified == initial_dot
AssertionError

  _warn_unhandled_exception()
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py", line 2043, in _really_load
    assert domain_specified == initial_dot
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 967, in main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 927, in _real_main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 737, in __init__
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3855, in _setup_opener
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 108, in load_cookies
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 1658, in load
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/cookiejar.py", line 2071, in _really_load
    raise LoadError("invalid Netscape format cookies file %r: %r" %
http.cookiejar.LoadError: invalid Netscape format cookies file '/data/user/0/com.junkfood.seal/cache/cookies.txt': 'twitter.com\tTRUE\t/\tTRUE\t0\tguest_id_ads\tv1%3A167786805370474302'

### Screenshots & Screen Records

![Screenshot_2023-03-03-23-58-41-74_2b0c70832456616f1f794bb05bb8d2fa](https://user-images.githubusercontent.com/123523228/222804366-75c89f9e-5ff9-4633-a5e4-cff2e5bc02bf.jpg)

### Device info

App version: 1.8.2 (10820)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.02.17

**Comment by Marco-9456** [comment]
> Dude, why the hell didn't you mention that the link leads to NSFW content?

**Comment by JunkFood02** [comment]
Update to v1.9.0-beta.3 or simply turn off cookies
