### ISSUE TITLE
Can't Download

### ISSUE THREAD

**Issue by amir385276** [JunkFood02/Seal#747]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

App version: 1.9.2 (10920)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: https://youtu.be/bfOY-SNnn3E
[debug] Command-line config: ['--no-mtime', '--cookies', '/data/user/0/com.junkfood.seal/cache/cookies.txt', '-v', '-r', '1000K', '--no-playlist', '--downloader', 'libaria2c.so', '--external-downloader-args', 'aria2c:"--summary-interval=1"', '-S', 'ext,res:1080,acodec:opus', '--write-auto-subs', '--extractor-args', 'youtube:skip=translated_subs', '--sub-langs', 'en.*,.*-orig,.srt', '--write-subs', '--embed-chapters', '--write-thumbnail', '--convert-thumbnails', 'png', '-P', '/storage/emulated/0/Download/Seal', '-P', 'temp:/data/user/0/com.junkfood.seal/cache/tmp', '-o', '%(title).200B [%(id)s].%(ext)s', '--no-cache-dir', '--ffmpeg-location', '/data/app/~~qU2D4o_sNv9bkypSDHfckg==/com.junkfood.seal-W0OZB4JdbUw3pu9i9mQFRw==/lib/arm64/libffmpeg.so', 'https://youtu.be/bfOY-SNnn3E']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-4.19.157-perf-g836e7cd4cf74-aarch64-with-libc (OpenSSL 1.1.1d 10 Sep 2019, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: mutagen-1.46.0, no_Cryptodome-None, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] [youtube] Extracted SAPISID cookie
[debug] Sort order given by user: ext, res:1080, acodec:opus
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, vext, aext, res:1080(1080.0), acodec:opus(12), quality, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
ERROR: [Errno 2] No such file or directory: "/storage/emulated/0/Download/Seal/KATE COMPTON SEXY VALENTINE'S DAY LINGERIE TRY-ON HAUL ｜ [YANDY.COM](http://yandy.com/) [bfOY-SNnn3E].en-orig.vtt"
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 2779, in process_video_result
    self.process_info(new_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3037, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3997, in _write_subtitles
    existing_sub = self.existing_file((sub_filename_final, sub_filename))
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 2979, in existing_file
    os.remove(file)
FileNotFoundError: [Errno 2] No such file or directory: "/storage/emulated/0/Download/Seal/KATE COMPTON SEXY VALENTINE'S DAY LINGERIE TRY-ON HAUL ｜ [YANDY.COM](http://yandy.com/) [bfOY-SNnn3E].en-orig.vtt"

### Device info

1.9.2

**Comment by JunkFood02** [comment]
Turn off download subtitle and try again

**Comment by amir385276** [comment]
Hi
there is no download and the bug is still there

App version: 1.9.2 (10920)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: https://youtu.be/bfOY-SNnn3E
[debug] Command-line config: ['--no-mtime', '--cookies', '/data/user/0/com.junkfood.seal/cache/cookies.txt', '-v', '-r', '1000K', '--no-playlist', '--downloader', 'libaria2c.so', '--external-downloader-args', 'aria2c:"--summary-interval=1"', '-S', 'ext,res:1080,acodec:opus', '--embed-chapters', '--write-thumbnail', '--convert-thumbnails', 'png', '-P', '/storage/emulated/0/Download/Seal', '-P', 'temp:/data/user/0/com.junkfood.seal/cache/tmp', '-o', '%(title).200B [%(id)s].%(ext)s', '--no-cache-dir', '--ffmpeg-location', '/data/app/~~qU2D4o_sNv9bkypSDHfckg==/com.junkfood.seal-W0OZB4JdbUw3pu9i9mQFRw==/lib/arm64/libffmpeg.so', 'https://youtu.be/bfOY-SNnn3E']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-4.19.157-perf-g836e7cd4cf74-aarch64-with-libc (OpenSSL 1.1.1d 10 Sep 2019, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: mutagen-1.46.0, no_Cryptodome-None, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] [youtube] Extracted SAPISID cookie
[debug] Sort order given by user: ext, res:1080, acodec:opus
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, vext, aext, res:1080(1080.0), acodec:opus(12), quality, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] ffmpeg command line: '/data/app/~~qU2D4o_sNv9bkypSDHfckg==/com.junkfood.seal-W0OZB4JdbUw3pu9i9mQFRw==/lib/arm64/libffmpeg.so' -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:/data/user/0/com.junkfood.seal/cache/tmp/KATE COMPTON SEXY VALENTINE'"'"'S DAY LINGERIE TRY-ON HAUL ｜ [YANDY.COM](http://yandy.com/) [bfOY-SNnn3E].webp' -update 1 -movflags +faststart 'file:/data/user/0/com.junkfood.seal/cache/tmp/KATE COMPTON SEXY VALENTINE'"'"'S DAY LINGERIE TRY-ON HAUL ｜ [YANDY.COM](http://yandy.com/) [bfOY-SNnn3E].png'
WARNING: Replacing existing file "/storage/emulated/0/Download/Seal/KATE COMPTON SEXY VALENTINE'S DAY LINGERIE TRY-ON HAUL ｜ [YANDY.COM](http://yandy.com/) [bfOY-SNnn3E].png"
ERROR: [Errno 2] No such file or directory: "/storage/emulated/0/Download/Seal/KATE COMPTON SEXY VALENTINE'S DAY LINGERIE TRY-ON HAUL ｜ [YANDY.COM](http://yandy.com/) [bfOY-SNnn3E].png"
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 2779, in process_video_result
    self.process_info(new_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3323, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3503, in post_process
    info = self.run_pp(MoveFilesAfterDownloadPP(self), info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3462, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/movefilesafterdownload.py", line 42, in run
    os.remove(encodeFilename(newfile))
FileNotFoundError: [Errno 2] No such file or directory: "/storage/emulated/0/Download/Seal/KATE COMPTON SEXY VALENTINE'S DAY LINGERIE TRY-ON HAUL ｜ [YANDY.COM](http://yandy.com/) [bfOY-SNnn3E].png"

thanks a lot

**Comment by amir385276** [comment]
I do turn off subtitle

**Comment by JunkFood02** [comment]
i see, it looks like the title of the video has some invalid characters which failed the download. Does it occurs in other downloads or only with this video?
