### ISSUE TITLE
beta 2 execute error !

### ISSUE THREAD

**Issue by root-kernelhacker** [JunkFood02/Seal#776]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Beta 1 has no such errors.  If you update to beta 2 while beta 1 is installed, the error does not occur, but if you delete beta 1 and install beta 2, the error occurs.

App version: 1.10.0-beta.2 (10920)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 

java.lang.ExceptionInInitializerError
	at org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(SourceFile:546)
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(SourceFile:166)
	at okio.Okio.unzip(SourceFile:3)
	at com.yausername.youtubedl_android.YoutubeDL.initPython(SourceFile:49)
	at com.yausername.youtubedl_android.YoutubeDL.init(SourceFile:1)
	at com.junkfood.seal.App$onCreate$2.invokeSuspend(SourceFile:124)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:104)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:77)
	Suppressed: coil.network.HttpException: [StandaloneCoroutine{Cancelling}@e8e14ab, Dispatchers.IO]
Caused by: java.lang.RuntimeException: class org.apache.commons.compress.archivers.zip.AsiExtraField is not a concrete class
	at org.apache.commons.compress.archivers.zip.ExtraFieldUtils.register(Unknown Source:58)
	at org.apache.commons.compress.archivers.zip.ExtraFieldUtils.<clinit>(Unknown Source:9)
	... 11 more

### Error reports

Beta 1 has no such errors.  If you update to beta 2 while beta 1 is installed, the error does not occur, but if you delete beta 1 and install beta 2, the error occurs.

App version: 1.10.0-beta.2 (10920)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 

java.lang.ExceptionInInitializerError
	at org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(SourceFile:546)
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(SourceFile:166)
	at okio.Okio.unzip(SourceFile:3)
	at com.yausername.youtubedl_android.YoutubeDL.initPython(SourceFile:49)
	at com.yausername.youtubedl_android.YoutubeDL.init(SourceFile:1)
	at com.junkfood.seal.App$onCreate$2.invokeSuspend(SourceFile:124)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:104)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:77)
	Suppressed: coil.network.HttpException: [StandaloneCoroutine{Cancelling}@e8e14ab, Dispatchers.IO]
Caused by: java.lang.RuntimeException: class org.apache.commons.compress.archivers.zip.AsiExtraField is not a concrete class
	at org.apache.commons.compress.archivers.zip.ExtraFieldUtils.register(Unknown Source:58)
	at org.apache.commons.compress.archivers.zip.ExtraFieldUtils.<clinit>(Unknown Source:9)
	... 11 more

**Comment by root-kernelhacker** [comment]
Also, in beta 2, if you touch yt-dlp in the settings, a message saying that you cannot connect to the network appears.  In beta 1, a message appears saying that you are using the latest yt-dlp.

**Comment by root-kernelhacker** [comment]
Edit.  Cache existing seals.  After deleting all the data, the error occurs when beta 2 is executed unconditionally.  Seal 1.9.x, beta 1 has no problem, only beta 2 has an error.  The installation file is a v8a only build.

**Comment by root-kernelhacker** [comment]
Final cleanup.  
1. After installing beta 1, finish the configuration.  

2. After setting, check whether about 70MB of beta 1 app data has been created.  

3. Update to beta 2 later.  After several tests, the app data should be created about 70MB, but there is no error and it works.  In this state, the yt-dlp version check in the settings also works normally.  If you install beta 2 alone, app data is not created normally, and that seems to be the cause of the error.  (I guess, the message that there is no network connection is the cause of the error.)

**Comment by root-kernelhacker** [comment]
When installing beta 2 alone, the latest version of yt-dlp cannot be installed.  Please check the network connection status.  Perhaps, while the seal is running, the latest version of yt-dlp is installed, so it seems that about 70MB of app data is created, but beta 2 seems to have an error in the process.
