### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by soumyabratabose** [JunkFood02/Seal#80]
The app crashed after hitting download. The log file is given below. 

java.lang.IllegalArgumentException: Service not registered: com.junkfood.seal.MainActivity$a@46d0c31
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1759)
	at android.app.ContextImpl.unbindService(ContextImpl.java:1786)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:751)
	at com.junkfood.seal.MainActivity$b.a(SourceFile:2)
	at com.junkfood.seal.ui.page.download.DownloadViewModel$d.j(SourceFile:2)
	at s8.a.B(Unknown Source:8)
	at h9.k0.run(Unknown Source:86)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
	Suppressed: h9.i0: [w1{Cancelling}@eaea756, Dispatchers.Main.immediate]

**Comment by JunkFood02** [comment]
Hi, are you using the latest version v1.0.0?
