### ISSUE TITLE
[Bug] Command Line Error

### ISSUE THREAD

**Issue by b-risk** [JunkFood02/Seal#936]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Got error and can't download YT

### Error reports

App version: 1.9.2-(F-Droid) (10924)
Device information: Android 9 (API 28)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

URL: https://youtu.be/nQuJNiilKcQ
[debug] Command-line config: ['--no-mtime', '-v', '--no-playlist', '--concurrent-fragments', '8', '--embed-chapters', '--sponsorblock-remove', 'default', '-P', '/storage/emulated/0/Download/Seal', '-P', 'temp:/data/user/0/com.junkfood.seal/cache/tmp', '-o', '%(title).200B [%(id)s].%(ext)s', '--no-cache-dir', '--ffmpeg-location', '/data/app/com.junkfood.seal-lmLuvLUNg71b7i5t00jIzw==/lib/arm64/libffmpeg.so', 'https://youtu.be/nQuJNiilKcQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-4.4.146+-aarch64-with-libc (OpenSSL 1.1.1d  10 Sep 2019, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: mutagen-1.46.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/d0fd?service=YouTube&categories=%5B%22intro%22%2C+%22music_offtopic%22%2C+%22sponsor%22%2C+%22preview%22%2C+%22outro%22%2C+%22interaction%22%2C+%22selfpromo%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%2C+%22chapter%22%5D
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking http downloader on "https://rr4---sn-vgqsrnsy.googlevideo.com/videoplayback?expire=1689043515&ei=222sZIzKMOqX2_gPjvu1-A8&ip=2601%3A248%3A5380%3A5840%3Ad1de%3A845%3Adbe9%3Ade34&id=o-ABCFNxrpoCzyCHNr8hOCewLLfGA4ElpT2DYl30NiQ-fv&itag=248&source=youtube&requiressl=yes&mh=wj&mm=31%2C26&mn=sn-vgqsrnsy%2Csn-p5qlsn7d&ms=au%2Conr&mv=m&mvi=4&pl=38&initcwndbps=1655000&bui=AYlvQAs-cqASFV6OFJ0yJFq5inAeM7GhYNn4XW7ZrHFeacYDzNIpFUyCDSbizhYzgTFTRVgIWX4xn3Zxg7mzoTutmkVW-r62&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=418389929&dur=1420.767&lmt=1686550250463652&mt=1689021442&fvip=2&keepalive=yes&fexp=24007246%2C24363392&beids=24350017&c=IOS&txp=6319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgPCbkZs00c2sz51AidTG1wA6KR3inqL35ssFX0SIbYZgCIQDFPiCU3SFjYTTpICNCP1nt8AjmzOB0W2eDZjERX_RiBA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgCVqCknzjrOJDKhieIgWjF-N9abZaZ4O1bFnFcVd7bh8CIQCrxqEiYHNtwtiljOAKV3oPyZSXSi8TUmzphKjbbPWm6g%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[debug] Invoking http downloader on "https://rr4---sn-vgqsknld.googlevideo.com/videoplayback?expire=1689043516&ei=3G2sZJrOCum0lu8Pxt-LyAc&ip=2601%3A248%3A5380%3A5840%3Ad1de%3A845%3Adbe9%3Ade34&id=o-AIYto6soo5C3mXUH5XMpeQvyIcod1QGBSgRAPcKK6IYs&itag=251&source=youtube&requiressl=yes&mh=wj&mm=31%2C26&mn=sn-vgqsknld%2Csn-p5qddn7k&ms=au%2Conr&mv=m&mvi=4&pl=38&initcwndbps=1696250&spc=Ul2Sq0MGE-PvZyOjODB4U39R93nfS7c&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=21937360&dur=1420.801&lmt=1686549587815168&mt=1689021442&fvip=5&keepalive=yes&fexp=24007246%2C51000024&beids=24350018&c=ANDROID&txp=6318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOoTlLZy2aRyy0Qjf1_S5Fs1Szkn9GnRt6VI9rWwDGEhAiEAoxp2CyCKPW81bZIbHo6w1i45mHtPGn6sSmOlhSzqhAU%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgWD6n6xlKpBBNfASVLHdTfIW5Icx5vpUtxg9MlCH-1_cCIHiHef23LpfS8ygibRXy7qSgy7vS5oOG0EZXSQZAaTeF"
ERROR: Unable to rename file: [Errno 2] No such file or directory: '/data/user/0/com.junkfood.seal/cache/tmp/battling crime - gmod darkrp trolling [nQuJNiilKcQ].f251.webm.part' -> '/data/user/0/com.junkfood.seal/cache/tmp/battling crime - gmod darkrp trolling [nQuJNiilKcQ].f251.webm'
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/common.py", line 241, in wrapper
    return func(self, *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/common.py", line 266, in try_rename
    os.replace(old_filename, new_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/com.junkfood.seal/cache/tmp/battling crime - gmod darkrp trolling [nQuJNiilKcQ].f251.webm.part' -> '/data/user/0/com.junkfood.seal/cache/tmp/battling crime - gmod darkrp trolling [nQuJNiilKcQ].f251.webm'

[debug] ffmpeg command line: /data/app/com.junkfood.seal-lmLuvLUNg71b7i5t00jIzw==/lib/arm64/libffmpeg.so -y -loglevel repeat+info -i 'file:/data/user/0/com.junkfood.seal/cache/tmp/battling crime - gmod darkrp trolling [nQuJNiilKcQ].f248.webm' -i 'file:/data/user/0/com.junkfood.seal/cache/tmp/battling crime - gmod darkrp trolling [nQuJNiilKcQ].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:/data/user/0/com.junkfood.seal/cache/tmp/battling crime - gmod darkrp trolling [nQuJNiilKcQ].temp.webm'
WARNING: Cannot update utime of file
ERROR: [Errno 2] No such file or directory: '/data/user/0/com.junkfood.seal/cache/tmp/battling crime - gmod darkrp trolling [nQuJNiilKcQ].temp.webm' -> '/data/user/0/com.junkfood.seal/cache/tmp/battling crime - gmod darkrp trolling [nQuJNiilKcQ].webm'
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1768, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 2897, in process_video_result
    self.process_info(new_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3439, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3621, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3603, in run_all_pps
    info = self.run_pp(pp, info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3581, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 838, in run
    os.rename(encodeFilename(temp_filename), encodeFilename(filename))
FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/com.junkfood.seal/cache/tmp/battling crime - gmod darkrp trolling [nQuJNiilKcQ].temp.webm' -> '/data/user/0/com.junkfood.seal/cache/tmp/battling crime - gmod darkrp trolling [nQuJNiilKcQ].webm'

### Device info

App version: 1.9.2-(F-Droid) (10924)
Device information: Android 9 (API 28)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

**Comment by b-risk** [comment]
Temporary folder is enabled
